# Generated by Django 5.0.1 on 2025-06-16 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_scolaire",
                    models.CharField(
                        blank=True,
                        help_text="Commission scolaire d'affiliation",
                        max_length=200,
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        blank=True,
                        help_text="École principale où vous travaillez",
                        max_length=200,
                    ),
                ),
                (
                    "grade_levels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Niveaux enseignés (optionnel)",
                    ),
                ),
                (
                    "subjects",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Matières enseignées (optionnel)",
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil d'enseignant",
                "verbose_name_plural": "Profils d'enseignants",
            },
        ),
    ]
